"""Keyless Azure AI Search hybrid retrieval with server-side entitlement filtering.

Per ADR-008/011: the access-control filter is always constructed here from
the caller's authenticated roles and sent to Azure AI Search as a server-side
`$filter`. A client can never widen its own entitlement by supplying a
filter; there is no code path that accepts one.

Authentication is keyless (`DefaultAzureCredential`), matching the Azure
OpenAI and Content Safety adapters. Embedding vectors are supplied by the
caller (the platform's local deterministic embedding, ADR-011) rather than
generated by this module.
"""

from typing import cast

from azure.core.credentials_async import AsyncTokenCredential
from azure.identity.aio import DefaultAzureCredential
from azure.search.documents.aio import SearchClient
from azure.search.documents.indexes.aio import SearchIndexClient
from azure.search.documents.indexes.models import (
    HnswAlgorithmConfiguration,
    SearchableField,
    SearchField,
    SearchFieldDataType,
    SearchIndex,
    SimpleField,
    VectorSearch,
    VectorSearchProfile,
)
from azure.search.documents.models import VectorizedQuery

from enterprise_genai_platform.rag.models import KnowledgeChunk

_VECTOR_PROFILE_NAME = "default-vector-profile"
_VECTOR_ALGORITHM_NAME = "default-hnsw"
_ROLE_DELIMITER = "|"

# The SDK's SearchFieldDataType is a runtime str-Enum, but its stubs resolve
# member access and .Collection(...) to a bare Enum, so mypy cannot see it as
# a str. Cast once here rather than scattering ignores through the schema.
_TYPE_STRING = cast(str, SearchFieldDataType.String)
_TYPE_STRING_COLLECTION = cast(
    str,
    SearchFieldDataType.Collection(SearchFieldDataType.String),  # type: ignore[operator]
)
_TYPE_SINGLE_COLLECTION = cast(
    str,
    SearchFieldDataType.Collection(SearchFieldDataType.Single),  # type: ignore[operator]
)


def build_role_filter(caller_roles: frozenset[str]) -> str:
    """Build a server-side OData filter admitting only chunks the caller may see.

    Requires every role a chunk declares to be held by the caller, matching
    `LocalVectorIndex`'s `chunk.allowed_roles <= caller_roles` semantics. An
    empty caller_roles set matches nothing: `search.in` against an empty list
    is never true, so `all()` over a chunk's (always non-empty, per ingestion
    validation) allowed_roles fails closed rather than open.

    `search.in` splits its target list on a delimiter with no per-element
    escaping, so a role containing that delimiter would silently be read as
    two roles. Rather than accept that ambiguity in an authorization filter,
    such a role is rejected outright; the platform's own role vocabulary
    (e.g. "agent.invoke") never contains one.
    """
    if any(_ROLE_DELIMITER in role for role in caller_roles):
        raise ValueError(f"Role values must not contain {_ROLE_DELIMITER!r}")
    escaped = sorted(role.replace("'", "''") for role in caller_roles)
    roles_csv = _ROLE_DELIMITER.join(escaped)
    return f"allowed_roles/all(r: search.in(r, '{roles_csv}', '{_ROLE_DELIMITER}'))"


class AzureSearchIndex:
    """Hybrid (BM25 + vector) Azure AI Search index behind the VectorIndex contract."""

    def __init__(
        self,
        *,
        endpoint: str,
        index_name: str,
        embedding_dimensions: int = 256,
        credential: AsyncTokenCredential | None = None,
    ) -> None:
        if not endpoint or not index_name:
            raise ValueError("Azure AI Search endpoint and index_name are required")
        if embedding_dimensions < 32:
            raise ValueError("embedding_dimensions must be at least 32")
        resolved_credential = credential or DefaultAzureCredential()
        self._index_name = index_name
        self._dimensions = embedding_dimensions
        self._search_client = SearchClient(endpoint, index_name, resolved_credential)
        self._index_client = SearchIndexClient(endpoint, resolved_credential)

    async def ensure_index(self) -> None:
        """Create or update the index schema; safe to call repeatedly (idempotent)."""
        index = SearchIndex(
            name=self._index_name,
            fields=[
                SimpleField(name="chunk_id", type=_TYPE_STRING, key=True),
                SimpleField(name="document_id", type=_TYPE_STRING, filterable=True),
                SearchableField(name="title", type=_TYPE_STRING),
                SimpleField(name="version", type=_TYPE_STRING),
                SimpleField(name="classification", type=_TYPE_STRING, filterable=True),
                SimpleField(
                    name="allowed_roles",
                    type=_TYPE_STRING_COLLECTION,
                    filterable=True,
                ),
                SearchableField(name="text", type=_TYPE_STRING),
                SimpleField(name="provenance_sha256", type=_TYPE_STRING),
                SearchField(
                    name="embedding",
                    type=_TYPE_SINGLE_COLLECTION,
                    searchable=True,
                    vector_search_dimensions=self._dimensions,
                    vector_search_profile_name=_VECTOR_PROFILE_NAME,
                ),
            ],
            vector_search=VectorSearch(
                profiles=[
                    VectorSearchProfile(
                        name=_VECTOR_PROFILE_NAME,
                        algorithm_configuration_name=_VECTOR_ALGORITHM_NAME,
                    )
                ],
                algorithms=[HnswAlgorithmConfiguration(name=_VECTOR_ALGORITHM_NAME)],
            ),
        )
        await self._index_client.create_or_update_index(index)

    async def add(self, chunks: tuple[KnowledgeChunk, ...]) -> None:
        """Upload authored chunks; ingestion validation happens before this call."""
        if not chunks:
            return
        documents = [
            {
                "chunk_id": chunk.chunk_id,
                "document_id": chunk.document_id,
                "title": chunk.title,
                "version": chunk.version,
                "classification": chunk.classification,
                "allowed_roles": sorted(chunk.allowed_roles),
                "text": chunk.text,
                "provenance_sha256": chunk.provenance_sha256,
                "embedding": list(chunk.embedding),
            }
            for chunk in chunks
        ]
        await self._search_client.merge_or_upload_documents(documents)

    async def search(
        self,
        query: str,
        query_embedding: tuple[float, ...],
        *,
        caller_roles: frozenset[str],
        limit: int,
    ) -> tuple[tuple[float, KnowledgeChunk], ...]:
        if len(query_embedding) != self._dimensions:
            raise ValueError("Embedding dimensions do not match")
        results = await self._search_client.search(
            search_text=query,
            filter=build_role_filter(caller_roles),
            vector_queries=[
                VectorizedQuery(
                    vector=list(query_embedding), k_nearest_neighbors=limit, fields="embedding"
                )
            ],
            select=[
                "chunk_id",
                "document_id",
                "title",
                "version",
                "classification",
                "allowed_roles",
                "text",
                "provenance_sha256",
            ],
            top=limit,
        )
        hits: list[tuple[float, KnowledgeChunk]] = []
        async for result in results:
            # RetrievalHit.score is bounded to [-1, 1] around LocalVectorIndex's
            # cosine similarity; Azure's hybrid RRF score is a different, unbounded
            # scale, so it is clamped rather than trusted to already fit.
            score = min(1.0, max(-1.0, float(result["@search.score"])))
            hits.append(
                (
                    score,
                    KnowledgeChunk(
                        chunk_id=result["chunk_id"],
                        document_id=result["document_id"],
                        title=result["title"],
                        version=result["version"],
                        classification=result["classification"],
                        allowed_roles=frozenset(result["allowed_roles"]),
                        text=result["text"],
                        provenance_sha256=result["provenance_sha256"],
                        # Not selected back from Azure (unused downstream by
                        # AuthorizedRetriever); left empty rather than faked.
                        embedding=(),
                    ),
                )
            )
        return tuple(hits)
